# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='title',
            new_name='album_title',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='title',
            new_name='song_title',
        ),
        migrations.AddField(
            model_name='album',
            name='album_logo',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='file_type',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
