# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20160913_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='song',
            name='file_type',
        ),
    ]
